development:
  host: localhost
  database: hackday_development

test:
  host: localhost
  database: hackday_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>